theme = "nord-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}/{total}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "sound"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "pacman"
interval = 300
format = "{pacman} updates"
format_singular = "{pacman} update"
format_up_to_date = "no updates"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-yourusername/ | wofi --show dmenui --normal-window"

[[block]]
block = "battery"
device = "/sys/class/power_supply/CMB1"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

